# To learn more about the options available and their functionality, please
# visit the config.yml documentation on GitHub:
# https://github.com/cervinakuy/KitPvP/wiki/config.yml

Items:
  Kits:
    Enabled: true
    Name: '&f选择职业 &8► &7右键单击'
    Material: CHEST
    Slot: 0
    Menu: true
    Commands: []
  Leave:
    Enabled: true
    Name: '&f返回大厅 &8► &7右键单击'
    Material: WATCH
    Slot: 8
    BungeeCord:
      Server: 主大厅
      Enabled: false
    Commands: []
Chat:
  Format: '%level% &r%player% &r%message%'
  Enabled: true
Combat:
  HitSound:
    Sound: BLAZE_HIT
    Pitch: 1
    Enabled: true
  ArrowHit:
    Message: '&f%player% &8| &c%health% ♥'
    Enabled: true
  ArrowReturn:
    ItemName: '&eReturnable Arrow'
    NoSpace: '%prefix% &cYou must have at least one slot open in your inventory for you to receive your arrow for your successful shot.'
    Enabled: true
    Count: 2
Kill:
  SoupReward:
    NoSpace: '%prefix% &c%amount% soups could not be added to your full inventory.'
    Amount: 1
    Delay: 0
    Enabled: false
  Commands: []
Death:
  Title:
    Title: '&c&l你死了'
    Subtitle: '&f将在 %seconds% 秒后重生'
    Time: 3
    Message: '%prefix% &f重生中...'
  Sound:
    Sound: AMBIENCE_THUNDER
    Pitch: 1
    Enabled: false
  Commands: []
  Messages:
    Player: '%prefix% &b%victim% &f被 &b%killer% &f击杀'
    PlayerQuit: '%prefix% &b%victim% &f被 &b%killer% &f打的离开了游戏'
    Shot: '%prefix% &b%victim% &f被 &b%killer% &f用弓箭击杀'
    Fall: '%prefix% &b%victim% &f摔死了'
    Void: '%prefix% &b%victim% &f掉出了这个世界'
    Fire: '%prefix% &b%victim% &f被烧死了'
    Explosion: '%prefix% &b%victim% &f爆炸了'
    Suicide: '%prefix% &b%victim% &f自杀了'
    Unknown: '%prefix% &b%victim% &f不知道怎么就死了'
    Enabled: true
Respawn:
  Commands: []
PlayerTracker:
  Name: '&aPlayer Tracker'
  Message: '&b&lTarget: &3%nearestplayer% &b&lDistance: &3%distance%'
  NoneOnline: '&cNo Players Online'
  TrackBelowY: 128
  RefreshOnlyWhenHeld: true
Soups:
  Name: '&aRegenerative Soups &7(Right Click)'
  RegenAmount: 6
  RemoveAfterUse: true
  Lore:
  - '&7Use this item to regain health.'
  Sound: EAT
  Pitch: 1
  Enabled: true
TNT:
  Name: '&aThrowable TNT &7(Right Click)'
  Enabled: true
PreviewMenuBackArrowCommands:
- 'player: kp menu'
Commands:
  Alias:
    Spawn: false
    Kit: false
    Kits: false
    Stats: false
Storage:
  Type: sqlite
  MySQL:
    Host: 127.0.0.1
    Port: 3306
    Database: kitpvp
    Username: root
    Password: password
Arena:
  ClearPotionEffectsOnJoin: true
  ClearInventoryOnJoin: true
  ClearInventoryOnLeave: false
  ClearInventoryOnRespawn: true
  ClearInventoryOnKit: true
  ClearKitOnCommandSpawn: true
  PreventBlockBreaking: true
  PreventBlockPlacing: true
  PreventItemDropping: true
  PreventHunger: true
  PreventItemDurabilityDamage: false
  PreventChestOpen: true
  PreventFallDamage: false
  PreventDeathDrops: true
  PreventArenaSignUseWithKit: true
  PreventItemCraft: true
  PreventSignChange: true
  KeepWeatherAtSunny: true
  GiveItemsOnClear: true
  GiveItemsOnRespawn: true
  GiveItemsOnJoin: true
  NoKitProtection: true
  FancyDeath: true
  ResetKillStreakOnLeave: true
  ToSpawnOnJoin: true
  DeathParticles: true
  AbilitiesRequireKit: true
  AddOverflowItemsOnKit: true
  DropRemainingOverflowItemsOnKit: true
  ResetMaxHealthOnDeath: true
Other:
  AutomaticallyAddKitToMenu: true
Spawn:
  Time: 5
  Enabled: true
PVPMode:
  Enable: true
  Time: 5000
